### PR TITLE
Remove the English description of OSGi event

### PR DESCRIPTION
**Pull request by SevenGan**
To avoid the misunderstanding of the language of meeting

### CODE REVIEW

**Comment by paulvi** [comment]
```
-<h3><a id="OSGi2017" href="#OSGi2017">OSGi Developer Outreach Event, March 28th 2017, 7pm/OSGi开发者拓展会议，2017年3月28日晚7点</a></h3>
 -The language of this event is Chinese. It will be hold in Huawei Shenzhen Base J Unit Training Center, from 19:00 to 21:30 on March 28th(<a href="https://www.google.com/maps/place/Huawei+Shenzhen+Base+J+Unit+Training+Center/@22.6520922,114.0614901,17z/data=!4m8!1m2!2m1!1sHuawei+training+center+Shenzhen!3m4!1s0x0:0x78d5d5e00c78e84d!8m2!3d22.6513939!4d114.0628307?hl=en">Google map</a>).
 -<img src="https://www.osgi.org/wp-content/uploads/OSGi-Header-Logo-e1463514096111.jpg">本次会议语言为中文，会议将在3月28晚7点到9点半在深圳坂田华为基地J区培训中心举办。（ <a href="http://map.baidu.com/?shareurl=1&poiShareUid=669431e72e02e4466140a91c">Baidu map</a>）
 +<h3><a id="OSGi2017" href="#OSGi2017">OSGi联盟2017年开发者拓展会议 - 万物互联与OSGi(2017年3月28日晚7点，坂田华为基地,免费向所有人开放)</a></h3>
 +<img src="https://www.osgi.org/wp-content/uploads/OSGi-Header-Logo-e1463514096111.jpg">本次为中文会议，对所有OSGi兴趣爱好者免费开放。会议将在3月28晚7点到9点半在深圳坂田华为基地J区培训中心举办。（ <a href="http://map.baidu.com/?shareurl=1&poiShareUid=669431e72e02e4466140a91c">Baidu map</a>）
  <p>Topics | 主题</p>
  <ul>
 -    <li>19:00 : Welcome & Intro/开场介绍 - Kai Hackbarth (Bosch & OSGi Alliance Board Member)</li>
 -    <li>19:10 : China OSGi Users’ Forum/中国OSGi用户论坛 - Jeff Liu (Richstone Data Technologies)</li>    
 -    <li>19:20 : OSGi and IoT/OSGi和物联网 - Seven (Huawei)</li>
 -    <li>20:00 : OSGi tooling - experiences from implementing OSGi based solutions at Liferay /OSGi工具 - Liftray基于OSGi解决方案的实践分享 - Terry Jia (Liferay)</li>
 -    <li>20:40 : How Bosch is building open IoT ecosystems using OSGi/博世如何用OSGi构建IoT生态 - Xie Chao (Bosch)</li>
 +    <li>19:00 : 开场介绍 - Kai Hackbarth (Bosch & OSGi联盟)</li>
 +    <li>19:10 : 中国OSGi用户论坛 - Jeff Liu (Richstone Data Technologies)</li>    
 +    <li>19:20 : OSGi和物联网 - 甘璐 (华为)</li>
 +    <li>20:00 : OSGi工具 - Liftray基于OSGi解决方案的实践分享 - Terry Jia (Liferay)</li>
 +    <li>20:40 : 博世如何用OSGi构建IoT生态 - Xie Chao (Bosch)</li>
  </ul>
 -<p>Huawei <img src="http://www.huawei.com/minisite/error/404-en_files/logo_new.png" width="100" height="25"> provides some soft drinks and tea. 华为为本次会议提供软饮和茶水。</p> 
 -<p>OSGi alliance <img src="https://www.osgi.org/wp-content/uploads/OSGi-Header-Logo-e1463514096111.jpg" width="100" height="37"> provides some fast food. OSGi联盟为本次会议提供一些快餐。</p> 
 -<p>This meeting is free, but the identity of participants need to be checked at the front door. Please register first. 本次会议是公开免费的，但是由于入场时门卫需要检查您的身份信息，需要您先进行注册。</p>
 -<p>Register at /注册链接 <a href="https://yoopay.cn/event/osgidevevent2017">https://yoopay.cn/event/osgidevevent2017</a></p>
 -or below  
 +<p>Huawei<img src="http://www.huawei.com/minisite/error/404-en_files/logo_new.png" width="100" height="25">为本次会议提供软饮和茶水。</p> 
 +<p>OSGi联盟<img src="https://www.osgi.org/wp-content/uploads/OSGi-Header-Logo-e1463514096111.jpg" width="100" height="37">为本次会议提供一些点心和水果。</p> 
 +<p>本次会议是公开免费的，但是由于入场时门卫需要检查您的身份信息，需要您先进行注册。</p>
 +<p>注册链接 <a href="https://yoopay.cn/event/osgidevevent2017">https://yoopay.cn/event/osgidevevent2017</a></p>
 +或者点击下附注册按钮  
```

**Comment by paulvi** [comment]
English as additional could be OK as well.

**Comment by SevenGan** [comment]
Hi Paul, it's a suggestion of another participant. They said English description makes them confusion about the presentation language of the event.

Thank you!:)

**Comment by paulvi** [comment]
OK

**Comment by paulvi** [comment]
在 https://yoopay.cn/event/osgidevevent2017 都是中文

@SevenGan 但是没有提醒 SZJUG

**Pull request merged**
